baseURL = "https://allwens.work/"
languageCode = "zh-cn"
title = "Hoar"
theme = "yinyang"
DefaultContentLanguage = "cn"

[author]
name = "amtoaer"
homepage = "https://allwens.work/"

[params]
headTitle = "Hoar"
mainSections = ["posts"]
gitalk = true


[[params.socials]]
name = "Github"
link = "https://github.com/amtoaer"
